import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";

// Metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Geist font CDN */}
        <link
          rel="stylesheet"
          href="https://unpkg.com/@geist-ui/react/fonts/Geist.css"
        />
        {/* Add Geist Mono font CDN */}
        <link
          rel="stylesheet"
          href="https://unpkg.com/@geist-ui/react/fonts/GeistMono.css"
        />
      </head>
      <body className="font-geist flex flex-col min-h-screen">
        {/* Global Header */}
        <Header />

        {/* Main Content */}
        <main className="flex-1 w-full px-4 sm:px-6 md:px-10 lg:px-16 xl:px-24 2xl:px-32 max-w-screen-2xl mx-auto">
          {children}
        </main>

        {/* Global Footer */}
        <Footer />
      </body>
    </html>
  );
}
